/**
 * Fixture válida — Peugeot 2008 Griffe 1.6 Flex Automático 2017.
 *
 * Demonstra:
 * - timing_system = "correia_dentada"
 * - transmission_type = "automatico" + preventiva_recomendada
 * - bundles: kit_troca_oleo_motor, kit_revisao_completa,
 *   kit_correia_dentada (safe_to_buy, requires_compatibility_confirmation)
 *   e kit_cambio_automatico (inspect_before_buy, sem compra direta)
 * - purchase_bundle_keys nos milestones
 * - severe_use_rules, age_based_alerts, fixed_intervals,
 *   not_applicable_items, general_notes, safety_disclaimer e metadata
 */

import {
  MAINTENANCE_PLAN_SCHEMA_VERSION,
  type MaintenancePlanJson,
} from "../../maintenance-plan-schema";

export const peugeot2008_2017Plan: MaintenancePlanJson = {
  schema_version: MAINTENANCE_PLAN_SCHEMA_VERSION,
  vehicle_summary: {
    display_name: "Peugeot 2008 Griffe 1.6 Flex Automático 2017",
    marca: "Peugeot",
    modelo_fipe: "2008 Griffe 1.6 Flex 16V 5p Aut.",
    ano_modelo: 2017,
    combustivel: "Flex",
    cilindradas: 1600,
    motor_textual: "1.6 16V Flex",
    valvulas: 16,
    transmissao: "automatico",
  },
  base_rules: {
    revision_interval_km: 10000,
    revision_interval_months: 12,
    max_planned_km: 200000,
    severe_use_oil_interval_km: 5000,
    severe_use_oil_interval_months: 6,
  },
  system_profile: {
    timing_system: "correia_dentada",
    transmission_type: "automatico",
    transmission_service_policy: "preventiva_recomendada",
    transmission_fluid_service_type: "desconhecido",
    cooling_system_policy: "Troca preventiva do fluido a cada 60.000 km ou 4 anos.",
  },
  milestones: [
    {
      km: 10000,
      label: "1ª revisão — 10.000 km",
      revision_number: 1,
      items: [
        {
          item_key: "oleo_motor",
          label: "Óleo do motor",
          category: "motor",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 10000,
          interval_months: 12,
          confidence: 95,
          source_type: "manual",
        },
        {
          item_key: "filtro_oleo",
          label: "Filtro de óleo",
          category: "filtros",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 10000,
          interval_months: 12,
          confidence: 95,
          source_type: "manual",
        },
        {
          item_key: "filtro_cabine",
          label: "Filtro de cabine (ar-condicionado)",
          category: "filtros",
          action: "inspecionar",
          recommendation_type: "inspect_only",
          shopping_classification: "inspect_before_buy",
          applies: true,
          confidence: 80,
          source_type: "manual",
        },
      ],
      purchase_bundle_keys: ["kit_troca_oleo_motor"],
    },
    {
      km: 20000,
      label: "2ª revisão — 20.000 km",
      revision_number: 2,
      items: [
        {
          item_key: "oleo_motor",
          label: "Óleo do motor",
          category: "motor",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          confidence: 95,
          source_type: "manual",
        },
        {
          item_key: "filtro_oleo",
          label: "Filtro de óleo",
          category: "filtros",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          confidence: 95,
          source_type: "manual",
        },
        {
          item_key: "filtro_ar_motor",
          label: "Filtro de ar do motor",
          category: "filtros",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 20000,
          confidence: 90,
          source_type: "manual",
        },
        {
          item_key: "filtro_cabine",
          label: "Filtro de cabine",
          category: "filtros",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 20000,
          confidence: 90,
          source_type: "manual",
        },
        {
          item_key: "filtro_combustivel",
          label: "Filtro de combustível",
          category: "filtros",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 20000,
          confidence: 88,
          source_type: "manual",
        },
      ],
      purchase_bundle_keys: ["kit_revisao_completa"],
    },
    {
      km: 40000,
      label: "4ª revisão — 40.000 km",
      revision_number: 4,
      items: [
        {
          item_key: "oleo_motor",
          label: "Óleo do motor",
          category: "motor",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          confidence: 95,
          source_type: "manual",
        },
        {
          item_key: "filtro_oleo",
          label: "Filtro de óleo",
          category: "filtros",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          confidence: 95,
          source_type: "manual",
        },
        {
          item_key: "velas_ignicao",
          label: "Velas de ignição",
          category: "ignicao",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "safe_to_buy",
          applies: true,
          interval_km: 40000,
          confidence: 90,
          source_type: "manual",
        },
        {
          item_key: "fluido_freio",
          label: "Fluido de freio",
          category: "freios",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "safe_to_buy",
          applies: true,
          interval_km: 40000,
          interval_months: 24,
          confidence: 92,
          source_type: "manual",
        },
      ],
      purchase_bundle_keys: ["kit_revisao_completa"],
    },
    {
      km: 60000,
      label: "6ª revisão — 60.000 km",
      revision_number: 6,
      items: [
        {
          item_key: "kit_correia_dentada",
          label: "Kit correia dentada (correia + tensor + bomba d'água)",
          category: "motor",
          action: "trocar",
          recommendation_type: "preventive_recommended",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 60000,
          interval_months: 60,
          confidence: 85,
          source_type: "experiencia_preventiva",
          reason:
            "Troca preventiva antecipada para evitar quebra de correia dentada em motor de interferência.",
        },
        {
          item_key: "correia_acessorios",
          label: "Correia de acessórios",
          category: "motor",
          action: "trocar",
          recommendation_type: "preventive_recommended",
          shopping_classification: "safe_to_buy",
          applies: true,
          interval_km: 60000,
          confidence: 80,
          source_type: "experiencia_preventiva",
        },
        {
          item_key: "fluido_arrefecimento",
          label: "Fluido de arrefecimento",
          category: "arrefecimento",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "safe_to_buy",
          applies: true,
          interval_km: 60000,
          interval_months: 48,
          confidence: 90,
          source_type: "manual",
        },
        {
          item_key: "oleo_cambio_automatico",
          label: "Fluido do câmbio automático",
          category: "transmissao",
          action: "troca_preventiva_recomendada",
          recommendation_type: "preventive_recommended",
          shopping_classification: "inspect_before_buy",
          applies: true,
          interval_km: 60000,
          confidence: 70,
          source_type: "experiencia_preventiva",
          reason:
            "Manual do fabricante não prevê troca, mas Jarvys recomenda inspeção e troca preventiva.",
        },
      ],
      purchase_bundle_keys: ["kit_correia_dentada", "kit_cambio_automatico"],
    },
    {
      km: 120000,
      label: "12ª revisão — 120.000 km",
      revision_number: 12,
      items: [
        {
          item_key: "kit_correia_dentada",
          label: "Kit correia dentada (2ª troca)",
          category: "motor",
          action: "trocar",
          recommendation_type: "required",
          shopping_classification: "bundle_preferred",
          applies: true,
          interval_km: 60000,
          confidence: 92,
          source_type: "manual",
        },
        {
          item_key: "oleo_cambio_automatico",
          label: "Fluido do câmbio automático",
          category: "transmissao",
          action: "troca_preventiva_recomendada",
          recommendation_type: "preventive_recommended",
          shopping_classification: "inspect_before_buy",
          applies: true,
          confidence: 75,
          source_type: "experiencia_preventiva",
        },
      ],
      purchase_bundle_keys: ["kit_correia_dentada", "kit_cambio_automatico"],
    },
    {
      km: 200000,
      label: "Marco projetado — 200.000 km",
      projected: true,
      items: [
        {
          item_key: "diagnostico_geral",
          label: "Diagnóstico geral preventivo",
          category: "diagnostico",
          action: "diagnosticar",
          recommendation_type: "inspect_only",
          shopping_classification: "service_only",
          applies: true,
          confidence: 70,
          source_type: "experiencia_preventiva",
        },
      ],
      notes: [
        "Marco projetado pelo Jarvys além do cronograma oficial do fabricante.",
      ],
    },
  ],
  fixed_intervals: [
    {
      item_key: "palhetas",
      label: "Palhetas do limpador",
      category: "conforto",
      action: "trocar",
      interval_months: 12,
      shopping_classification: "safe_to_buy",
      recommendation_type: "recommended",
      applies: true,
      confidence: 80,
      source_type: "experiencia_preventiva",
    },
  ],
  severe_use_rules: [
    {
      item_key: "oleo_motor",
      label: "Óleo do motor — uso severo",
      description:
        "Em uso severo (trânsito intenso, GNV, viagens curtas), reduzir intervalo.",
      interval_km: 5000,
      interval_months: 6,
      recommendation_type: "preventive_recommended",
      source_type: "experiencia_preventiva",
      confidence: 85,
    },
  ],
  age_based_alerts: [
    {
      item_key: "bateria",
      label: "Bateria",
      trigger_age_years: 3,
      recommendation_type: "inspect_only",
      shopping_classification: "inspect_before_buy",
      reason: "Vida útil média de bateria gira em torno de 3 anos.",
      source_type: "experiencia_preventiva",
      confidence: 80,
    },
  ],
  not_applicable_items: [
    {
      item_key: "corrente_comando",
      label: "Corrente de comando",
      reason: "Motor 1.6 16V utiliza correia dentada, não corrente.",
      source_type: "manual",
      confidence: 95,
    },
  ],
  purchase_bundles: [
    {
      bundle_key: "kit_troca_oleo_motor",
      label: "Kit troca de óleo do motor",
      description: "Óleo recomendado + filtro de óleo.",
      bundle_type: "kit_troca_oleo_motor",
      item_keys: ["oleo_motor", "filtro_oleo"],
      category: "motor",
      shopping_classification: "safe_to_buy",
      preferred_search_query_template:
        "kit troca óleo {modelo} {motor} {ano_modelo}",
      required_item_keys: ["oleo_motor", "filtro_oleo"],
      requires_compatibility_confirmation: false,
      confidence: 90,
      source_type: "catalogo",
    },
    {
      bundle_key: "kit_revisao_completa",
      label: "Kit revisão completa",
      description:
        "Óleo + filtro de óleo + filtro de ar + filtro de cabine + filtro de combustível.",
      bundle_type: "kit_revisao_completa",
      item_keys: [
        "oleo_motor",
        "filtro_oleo",
        "filtro_ar_motor",
        "filtro_cabine",
        "filtro_combustivel",
      ],
      category: "filtros",
      shopping_classification: "bundle_preferred",
      preferred_search_query_template:
        "kit revisão {modelo} {motor} {ano_modelo}",
      required_item_keys: [
        "oleo_motor",
        "filtro_oleo",
        "filtro_ar_motor",
        "filtro_cabine",
        "filtro_combustivel",
      ],
      requires_compatibility_confirmation: true,
      confidence: 85,
      source_type: "catalogo",
    },
    {
      bundle_key: "kit_correia_dentada",
      label: "Kit correia dentada",
      description: "Correia + tensor + bomba d'água.",
      bundle_type: "kit_correia_dentada",
      item_keys: ["kit_correia_dentada"],
      category: "motor",
      shopping_classification: "safe_to_buy",
      preferred_search_query_template:
        "kit correia dentada {modelo} {motor} {ano_modelo}",
      required_item_keys: ["kit_correia_dentada"],
      requires_compatibility_confirmation: true,
      confidence: 82,
      source_type: "catalogo",
    },
    {
      bundle_key: "kit_cambio_automatico",
      label: "Kit câmbio automático",
      description:
        "Fluido específico + filtro(s) + junta. Exige confirmação de tipo de câmbio antes da compra.",
      bundle_type: "kit_cambio_automatico",
      item_keys: ["oleo_cambio_automatico"],
      category: "transmissao",
      shopping_classification: "inspect_before_buy",
      preferred_search_query_template:
        "kit câmbio automático {modelo} {motor} {ano_modelo}",
      required_item_keys: ["oleo_cambio_automatico"],
      requires_compatibility_confirmation: true,
      confidence: 60,
      source_type: "experiencia_preventiva",
      notes: [
        "Nunca virar link de compra direto sem confirmação do tipo de câmbio e filtros internos.",
      ],
    },
  ],
  general_notes: [
    "Plano preventivo Jarvys baseado em manual e experiência de campo.",
  ],
  safety_disclaimer:
    "Sempre confirme com profissional de confiança antes de executar serviços.",
  metadata: {
    generated_at: "2026-06-27T00:00:00.000Z",
    generated_by: "curadoria",
    source: "curadoria",
    overall_confidence: 85,
    reviewed_by_admin: true,
    schema_notes: ["Fixture de teste — não usar em produção."],
  },
};
