/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as RevisoesRouteImport } from './routes/revisoes'
import { Route as GaragemRouteImport } from './routes/garagem'
import { Route as DespesasRouteImport } from './routes/despesas'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisoesRoute = RevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GaragemRoute = GaragemRouteImport.update({
  id: '/garagem',
  path: '/garagem',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/despesas': typeof DespesasRoute
  '/garagem': typeof GaragemRoute
  '/revisoes': typeof RevisoesRoute
  '/shopping': typeof ShoppingRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/despesas': typeof DespesasRoute
  '/garagem': typeof GaragemRoute
  '/revisoes': typeof RevisoesRoute
  '/shopping': typeof ShoppingRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/despesas': typeof DespesasRoute
  '/garagem': typeof GaragemRoute
  '/revisoes': typeof RevisoesRoute
  '/shopping': typeof ShoppingRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/despesas'
    | '/garagem'
    | '/revisoes'
    | '/shopping'
    | '/signup'
    | '/splash'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/despesas'
    | '/garagem'
    | '/revisoes'
    | '/shopping'
    | '/signup'
    | '/splash'
    | '/welcome'
  id:
    | '__root__'
    | '/despesas'
    | '/garagem'
    | '/revisoes'
    | '/shopping'
    | '/signup'
    | '/splash'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DespesasRoute: typeof DespesasRoute
  GaragemRoute: typeof GaragemRoute
  RevisoesRoute: typeof RevisoesRoute
  ShoppingRoute: typeof ShoppingRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisoes': {
      id: '/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof RevisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garagem': {
      id: '/garagem'
      path: '/garagem'
      fullPath: '/garagem'
      preLoaderRoute: typeof GaragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DespesasRoute: DespesasRoute,
  GaragemRoute: GaragemRoute,
  RevisoesRoute: RevisoesRoute,
  ShoppingRoute: ShoppingRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
